modLoader="javafml"
loaderVersion="[43,)"
license="All rights reserved"
[[mods]]
modId="ghosts"
version="1.0.0"
displayName="Ghosts"
displayURL="https://wanmine.net/"
logoFile="logo.png"
credits="Diamantino Op"
authors="WanMine"
description='''
Adds two entities in the game
'''

[[dependencies.ghosts]]
    modId="forge"
    mandatory=true
    versionRange="[43,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ghosts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19.2,1.20)"
    ordering="NONE"
    side="BOTH"
