modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
[[mods]]
modId="ghosts"
version="${version}"
displayName="Ghosts"
displayURL="https://wanmine.net/"
logoFile="logo.png"
credits="Diamantino Op"
authors="WanMine"
description='''
Adds two entities in the game
'''

[[dependencies.ghosts]]
    modId="forge"
    mandatory=true
    versionRange="[47,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.ghosts]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
